export const BRING_ALL = 'bring_all'
export const LOADING = 'loading'
export const ERROR = 'error'
export const CHANGE_TITLE = 'change_title'
export const CHANGE_BODY = 'change_body'
export const POST_ADDED = 'post_added'